os: linux
dist: focal
language: java
jdk: oraclejdk15
services: 
  - xvfb
  - mysql

addons:
  sonarcloud:
    organization: "stefanobelli"
    token: $SONAR_TOKEN
      
before_script:
  - sudo mysql -u root -e "source res/createWhorkDbSchema.sql"

script:
  - mvn clean compile
  - mvn jacoco:prepare-agent test jacoco:report

after_success:
  - sonar-scanner

before_deploy:
  - sudo apt update
  - sudo apt install -y texlive-full
  - bash make-packages.sh

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  skip_cleanup: true
  file:
    - whork-app-$TRAVIS_TAG-noosx-linuxany-win32oraclejdk8.jar
    - whork-docs-$TRAVIS_TAG.zip
    - createWhorkDbSchema-$TRAVIS_TAG.zip
  on:
    tags: true
