/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2020-12-25 16:22:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import logic.dao.StatoOccupazionaleDao;

public final class Register_002dcandidate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("logic.dao.StatoOccupazionaleDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("/RegisterChoiceServlet\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t\t<title>Registrazione</title>\n");
      out.write("\t</head>\n");
      out.write("\t\n");
      out.write("\t<body lang=\"it\">\n");
      out.write("\t\t\n");
      out.write("\t\t<form>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"email\"> Email</label>\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"register\" id=\"email\" placeholder=\"Inserisci la tua email\">\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"password\"> Password</label>\n");
      out.write("\t\t\t\t<input type=\"password\" name=\"register\" id=\"password\" placeholder=\"Inserisci la tua password\">\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"confirm-password\"> Conferma Password</label>\n");
      out.write("\t\t\t\t<input type=\"password\" name=\"register\" id=\"confirm-password\" placeholder=\"Conferma la tua password\">\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<p><b>Dati Personali</b></p>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"name\"> Nome </label>\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"register\" id=\"name\" placeholder=\"Inserisci il tuo nome\">\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"surname\"> Cognome </label>\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"register\" id=\"surname\" placeholder=\"Inserisci il tuo cognome\">\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"fiscal-code\"> Codice Fiscale </label>\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"register\" id=\"fiscal-code\" placeholder=\"Inserisci il tuo codice fiscale\">\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p><b>Dati di contatto</b></p>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"town\"> Comune </label>\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"register\" id=\"town\" placeholder=\"Inserisci il tuo comune\">\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"address\"> Indirizzo </label>\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"register\" id=\"address\" placeholder=\"Inserisci il tuo indirizzo\">\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t<label for=\"phone-number\"> Cellulare </label>\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"register\" id=\"phone-number\" placeholder=\"Inserisci il tuo numero di telefono\">\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<p>\t\t\t\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"register\" id=\"province\" placeholder=\"Provincia\">\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"register\" id=\"cap\" placeholder=\"CAP\">\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<p><b>Stato Occupazionale</b></p>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<select name=\"employment-status\" size=\"1\">\n");
      out.write("\t\t\t\t<option>Italia</option>\n");
      out.write("\t\t\t\t<option>Inghilterra</option>\n");
      out.write("\t\t\t\t<option>Francia</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t</form>\n");
      out.write("\t\t\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
