# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup MySQL without requiring root password
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
    - name: Create whorkdb
      run: sudo mysql -u root -e "source res/createWhorkDbSchema.sql"
    - name: Build, test and compute code coverage
      run: mvn clean compile jacoco:prepare-agent test jacoco:report
    - name: Static analysis scan (SonarCloud)
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
